# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Primes"); Pkg.test("Primes"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Coverage"); Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Primes")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Primes")); include(joinpath("docs", "make.jl"))'
